### PR TITLE
Appended a conference in list.

### PR DESCRIPTION
**Pull request by yashsoni369**
First time contribution to open source project

## In this pull request
- [x]  I am adding a new resource.
- [x]  I am adding a new step
- [x]  I am providing an edit
- [ ] Removing a resource

## Adding new resource
* The resource I am adding is _ _ _ _
* I am adding this resource to _ _ _ _ step.
* I think this resource deserves to be in this list because _ _ _ _

**Do not add more than one during hacktoberfest**

## Add new step
* The step I am adding is _ _ _ _
* The reason why I think this step should be there is because _ _ _ _
* - [x] I have added at least one resource to this step 

**Do not add more than one during hacktoberfest**

## Providing an Edit
* The edit I am providing is to _ _ _ _

**Do not add more than one during hacktoberfest**

## Remove a resource
* The resource I am removing is _ _ _ _
* I am removing this resource from _ _ _ _ step.
* I think this resource should not be in this list because _ _ _ _

**Don't ask to remove stuff - unless you believe the content violates the code of conduct**

### CODE REVIEW

**Comment by yashsoni369** [comment]
First time open source contribution by following the guidelines !

**Review by codess-aus — APPROVED** [review]
Perfect, thank you

**Comment by codess-aus** [comment]
@all-contributors please add @Yash2737  for doc content

**Comment by codess-aus** [comment]
@all-contributors please add @Yash2737 for doc content

**Comment by codess-aus** [comment]
@all-contributors please add @Yash2737 for doc content

**Pull request merged**
