### PR TITLE
Learn most popular php framework

### PR DESCRIPTION
**Pull request by sam0hack**
## In this pull request
- [x]  I am adding a new resource.
- [ ]  I am adding a new step
- [ ]  I am providing an edit
- [ ] Removing a resource

## Adding a new resource
* The resource I am adding is coder's Tape
* I am adding this resource to 1 step.
* I think this resource deserves to be on this list because Php becomes very popular in the past years and so laravel which is a great framework and easy to learn.

### CODE REVIEW

**Review by codess-aus — CHANGES_REQUESTED** [review]
Hi @sam0hack,
Thanks so much for this recommendation, I'd love to have a Laravel track in there... but not specifically there. 
* We could have `[Coders Tape](https://www.youtube.com/c/CodersTape/)` in Section 8 - Subscribe to some YouTube Vids. 
* Or `[Laravel 6 Beginner](https://www.youtube.com/playlist?list=PLpzy7FIRqpGC8Jk6gyWdSVdxCVXZAsenQ)` in Section 3, Try some Code.

But we can't have `| [Learn most popular php framework (laravel)](https://www.youtube.com/c/CodersTape/featured) | Coder's Tape | 1 | Very good if you are a beginner and want to learn php in object orianted way |` in Section 1 - which is the What, Where, Why Section - as it's too specific - and also, the featured link starts playing an *Advanced PHP* Video, not a *Beginners* one.  See which option you like best, and then edit and submit that, and I'll merge you in ASAP

**Comment by sam0hack** [comment]
thanks, @msandfor I will fix it asap

**Comment by sam0hack** [comment]
@msandfor it's done.

**Review by codess-aus — APPROVED** [review]

**Comment by codess-aus** [comment]
Thanks for your Contribution @sam0hack 

@all-contributors please add @sam0hack  for doc content examples

**Comment by sam0hack** [comment]
Thank you :+1:

**Pull request merged**
