### PR TITLE
Suggested section of IDE Tools 

### PR DESCRIPTION
**Pull request by anothergeorgecoldham**
## In this pull request
- [X]  I am adding a new resource.
- [ ]  I am adding a new step
- [ ]  I am providing an edit
- [ ] Removing a resource

## Adding new resource
* The resource I am adding is a new section called Free Open Source Software Tools
* I am adding this resource to _ _ _ _ step. - New Section
* I think this resource deserves to be in this list because variety in tools.

**Do not add more than one during hacktoberfest**

## Add new step
* The step I am adding is _ _ _ _
* The reason why I think this step should be there is because _ _ _ _
* - [ ] I have added at least one resource to this step 

**Do not add more than one during hacktoberfest**

## Providing an Edit
* The edit I am providing is to _ _ _ _

**Do not add more than one during hacktoberfest**

## Remove a resource
* The resource I am removing is _ _ _ _
* I am removing this resource from _ _ _ _ step.
* I think this resource should not be in this list because _ _ _ _

**Don't ask to remove stuff - unless you believe the content violates the code of conduct**

### CODE REVIEW

**Review by codess-aus — APPROVED** [review]

**Comment by anothergeorgecoldham** [comment]
Thanks :) I didn't sign up for hacktoberfest I just wanted to go through it to learn and have fun!

**Comment by codess-aus** [comment]
They'll plant a tree if you sign up and complete 4. Climate change needs more trees

**Comment by codess-aus** [comment]
@anothergeorgecoldham why not try this, if you just want to improve your profile and learn to build stuff on GitHub: https://www.aboutmonica.com/blog/how-to-create-a-github-profile-readme

**Comment by anothergeorgecoldham** [comment]
I read that the other night, thinking about it :)

**Comment by codess-aus** [comment]
@anothergeorgecoldham Did you see how pretty mine is? https://github.com/msandfor

**Comment by anothergeorgecoldham** [comment]
Yes, I've seen how pretty yours is :P I was going to add some badges or something to mine.

**Pull request merged**
